deleteInBatch(…) of JpaRepository which is different from delete(…) as it uses a query to delete the given entities which is more performant but comes with the side effect of ---not triggering the JPA-defined cascades--- (as the spec defines it).
SQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.

 java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at JPLISAgent.c line: 844